### PR TITLE
fix: uint8_t not in std

### PR DESCRIPTION
**Pull request by king-11**
- add header for std int
- fix for fedora install

### CODE REVIEW

**Comment by king-11** [comment]
image

**Comment by king-11** [comment]
gcc version 13.1.1
Fedora 38

**Review by vincenzopalazzo — COMMENTED** [review]
Not sure that this is the way to go.

To me this looks really strange.

Fedora ship the new gcc compiler (13) and I found that there is a bug with it https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107134

So as I would like that this will be fixed also for this kind of compiler, I think would be better to hide this under a `#ifdef GCC_13`

What do you think?

**Comment by king-11** [comment]
That sounds good to me I will make changes

**Comment by vincenzopalazzo** [comment]
Ok I did some modification on your code but I include it inside the official repo https://github.com/ZmnSCPxj/clboss/pull/169

Thanks!

**Comment by king-11** [comment]
Closing this for now

**Pull request closed without merging**
